name: Validar nombres de archivos

on:
  pull_request:
    branches:
      - main

jobs:
  validate-filenames:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Necesario para obtener los cambios en el PR

      - name: Validar nombres de archivos
        run: |
          echo "Archivos modificados:"
          git diff --name-only origin/main...HEAD > archivos.txt
          cat archivos.txt

          invalid=0
          while read archivo; do
            if [[ "$archivo" =~ [^a-zA-Z0-9._/-] ]]; then
              echo "❌ Nombre inválido: $archivo"
              invalid=1
            fi
          done < archivos.txt

          if [ $invalid -eq 1 ]; then
            echo "❌ Uno o más archivos tienen nombres inválidos."
            exit 1
          else
            echo "✅ Todos los nombres de archivo son válidos."
          fi
